### ISSUE TITLE
自定义分词器名称的问题

### ISSUE THREAD

**Issue by Tjatse** [medcl/elasticsearch-analysis-ik#106]
你好，一直在用ik，感觉非常好用，在这里表示感谢。
刚升级到ES2.0发现自定义的分词器无法使用了，由于我有几TB的历史数据和2013年到2015年按月分配的索引(xxx-201409这种样子的)，所以无法随意修改分词器名称至`ik_smart`或者`ik_max_word`，我的配置文件是：
```yaml
index:
  analysis:
    tokenizer:
      ik:
        type: org.elasticsearch.index.analysis.IkTokenizerFactory
        use_smart: false
    filter:
      aaa_synonym:
        type: synonym
        synonyms_path: ik/synonym/aaa.txt
      bbb_synonym:
        type: synonym
        synonyms_path: ik/synonym/bbb.txt
      ccc_synonym:
        type: synonym
        synonyms_path: ik/synonym/ccc.txt
    analyzer:
      ik:
        type: org.elasticsearch.index.analysis.IkAnalyzerProvider
        use_smart: false
      ik_term:
        type: org.elasticsearch.index.analysis.IkAnalyzerProvider
        use_smart: true
      ik_syno:
        type: custom
        tokenizer: ik
        filter: [aaa_synonym,bbb_synonym,ccc_synonym]
      default:
        type: ik
```

我的索引使用的是dynamic mapping，`analyzer`或`search_analyzer`是指向我自定义的`ik_term`, `ik_syno`，这样没办法修改mapping至`ik_smart` (reindex数据量太大，有上百亿条document)。
那么问题来了，`ik_term`我可以修改你的java代码把`ik_smart`改成`ik_term`后重新打包，但是像同义词(`ik_syno`)这种我改如何配置/修改代码？

附，按我目前的ES配置，会直接抛错：
```
nested: IllegalArgumentException[Unknown Tokenizer type [org.elasticsearch.index.analysis.IkTokenizerFactory] for [ik]];
```
