### ISSUE TITLE
ik_smart 加入同义词後ik_smart失效

### ISSUE THREAD

**Issue by squarehuang** [medcl/elasticsearch-analysis-ik#113]
我设置tokenizer: ik，再使用synonym token filter可以实现同义词功能，但use_smart参数设置不起作用，而单独设定 use_smart: true 是可以起作用的，是有少了什么设定吗? (ik_syno_smart)
望大神指教，谢谢

如 `阿里联手神州数码打造智慧城市`

输出如下
```
ik:                     阿里/ 里/ 联手/ 神州数码/ 神州/ 州/ 数码/ 打造/ 智慧/ 慧/ 城市
ik_smart:               阿里/ 联手/ 神州数码/ 打造/ 智慧/ 城市
ik_syno_smart:          阿里/ 里/ 联手/ 神州数码/ 神州/ 州/ 数码/ 數位/ 數碼/ 打造/ 智慧/ 慧/ 城市
```

elasticsearch.yml 设定如下

```
analyzer:
      ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_smart:
          type: custom
          use_smart: true
      ik_syno_smart:
          type: custom
          tokenizer: ik
          filter: [my_synonym_filter]
          use_smart: true
filter:
      my_synonym_filter:
          type: synonym
          synonyms_path: analysis/synonym.txt
```

ES 版本:1.72
IK 版本:1.4.1
