### ISSUE TITLE
ik-rtf版本如何配置同义词

### ISSUE THREAD

**Issue by naruto900814** [medcl/elasticsearch-analysis-ik#128]
```
filter:
      my_synonym:
        type: synonym
        synonyms_path: analysis/synonym.txt
    analyzer:
      ik:
        alias:
        - ik_analyzer
        type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word:
        type: ik
        use_smart: false
      ik_smart:
        type: ik
        use_smart: true
      mmseg:
        alias:
        - mmseg_analyzer
        type: org.elasticsearch.index.analysis.MMsegAnalyzerProvider
      ik_syno:
        type: custom
        tokenizer: ik
        filter: [my_synonym]
      ik_max_word_syno:
        type: custom
        tokenizer: ik
        filter: [my_synonym]
        use_smart: false
```

使用上面的配置在rtf启动时报错
