### ISSUE TITLE
关于分词设置的困惑

### ISSUE THREAD

**Issue by nathan-zhu** [medcl/elasticsearch-analysis-ik#243]
请教下，在配置文件elasticsearch.yml里设置ik 分词规则和 同义词，近义词与在 mapping 里指定有什么区别吗？配置里是所有索引都会走的吗？谁的优先级高？
elasticsearch.yml 里配置
```
index.analysis.analyzer.default.type: ik
index:
  analysis:
    analyzer:
      ik_syno:
          type: custom
          tokenizer: ik_max_word
          filter: [my_synonym_filter]
      ik_syno_smart:
          type: custom
          tokenizer: ik_smart
          filter: [my_synonym_filter]
    filter:
      my_synonym_filter:
          type: synonym
          synonyms_path: synonyms.txt
```
 mapping 下配置
```
{
  "settings": {
    "number_of_shards": 3,
    "number_of_replicas": 0,
    "index": {
      "analysis": {
        "analyzer": {
          "ik_syno": {
              "type": "custom",
              "tokenizer": "ik_max_word",
              "filter": ["my_synonym_filter"]
          },
          "ik_syno_smart": {
              "type": "custom",
              "tokenizer": "ik_smart",
              "filter": ["my_synonym_filter"]
          }
        },
        "filter": {
            "my_synonym_filter": {
              "type": "synonym",
              "synonyms_path": "synonyms.txt"
            }
        }
      }
    }    
  },
  "mapping": {}
}
```
按理说默认配置里的应该对所有索引都生效的，可是实际测试缺没有，请帮解释下多谢。
