### ISSUE TITLE
ik分词器ik_max_word和ik_smart单独可使用，作为属性不生效

### ISSUE THREAD

**Issue by sxhyll** [medcl/elasticsearch-analysis-ik#25]
如：
index:

  analysis:                   

```
analyzer:      

  ik:

      alias: [ik_analyzer]

      type: org.elasticsearch.index.analysis.IkAnalyzerProvider

  ik_max_word:

      type: ik

      use_smart: true

  ik_smart:

      type: ik

      use_smart: false
```

索引时用ik的话，按照配置应该选ik_max_word，因为ik_max_word设置的是true：
ik_max_word:

```
      type: ik

      use_smart: true
```

但是结果却是ik_smart的。

当我显式的在代码里用ik_max_word或ik_smart进行索引时，才生效，期待解决。

我用的是rails的这个插件：
https://github.com/karmi/retire
