### ISSUE TITLE
ik not found

### ISSUE THREAD

**Issue by wxlfight** [medcl/elasticsearch-analysis-ik#58]
es-version: 1.4.2
es-ik-version: 1.2.9

mvn package 打包得到jar包（已经在pom中将es修改到1.4.2版本），放到es plugin目录，并将config中ik目录放到es的config目录中，最后在elasticsearch.yml结尾中配置（我直接把我的配置复制过来）：
```yml
index: 
  analysis: 
    analyzer: 
      ik: 
        alias: [ik_analyzer]
        type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word: 
        type: ik
        use_smart: false
      ik_smart: 
        type: ik
        use_smart: true
```
运行命令：
```

curl -XPOST http://localhost:9200/index/fulltext/_mapping -d'
{
    "fulltext": {
             "_all": {
            "indexAnalyzer": "ik",
            "searchAnalyzer": "ik",
            "term_vector": "no",
            "store": "false"
        },
        "properties": {
            "content": {
                "type": "string",
                "store": "no",
                "term_vector": "with_positions_offsets",
                "indexAnalyzer": "ik",
                "searchAnalyzer": "ik",
                "include_in_all": "true",
                "boost": 8
            }
        }
    }
}'

返回出错：{"error":"MapperParsingException[Analyzer [ik] not found for field [content]]","status":400}
```

查了下，出现这样的错误是说yml配置文件格式有问题。
我了解yml缩进格式，冒号后面必须有一个空格，缩进时不能使用tab，而是使用1个或多个空格，按照这样的格式修改，并且在http://yaml-online-parser.appspot.com/ 上解析过，正常。

能否帮我看下是什么问题？
