### ISSUE TITLE
新人刚学习，求问一下ik这个是在哪儿设置，使得ik可以支持驼峰分词

### ISSUE THREAD

**Issue by hduyyg** [medcl/elasticsearch-analysis-ik#886]
```
index:
  analysis:
    tokenizer:
      my_ik:
        type: ik
        enable_lowercase: false
      my_ik_lowercase:
        type: ik
        enable_lowercase: true
    analyzer:
      my_ik_analyzer:
        type: ik
        enable_lowercase: false
        use_smart: true
```

_Originally posted by @medcl in https://github.com/medcl/elasticsearch-analysis-ik/issues/241#issuecomment-234825769_
